export interface KhachHangDto {
    id: string
    idkh: string
    madp: string
    madb: string
    sodb: string
    stt: number
    mamdsd: string
    malkh: string
    makv: string
    tenkh: string
    sonha: string
    maquan: string
    maphuong: string
    makhoi: string
    madpld: string
    sdt: string
    cmnd: string
    ngaycap: Date
    mst: string
    mahttt: string
    maldh: string
    madh: string
    namlapdat: number
    ngayht: Date
    ngaythaydh: Date
    ngaycup: Date
    ttsd: string
    loaicup: string
    isdm: boolean
    isdb: boolean
    chiatheongay: boolean
    kophimt: boolean
    kophitn: boolean
    isck: boolean
    tlck: number
    ishaigia: boolean
    istl: boolean
    tlsh: number
    tlcq: number
    tlsx: number
    tlkd: number
    m3SH: number
    m3CQ: number
    m3SX: number
    m3KD: number
    soho: number
    sonk: number
    tinhtheonk: boolean
    sdInfo_INHOADON: boolean
    tenkH_INHOADON: string
    diachI_INHOADON: string
    ishuy: boolean
    ngayhuy: Date
    kyhuy: Date
    kyapdung: Date
    ngayhethandh: Date
    m3CDSH1: number
    m3CDSH2: number
    m3CDSH3: number
    m3CDSH4: number
    m3CDCQ: number
    m3CDSX: number
    m3CDKD: number
    m3CDNT1: number
    m3CDNT2: number
    chisolaptdh: number
    isthaydhdb: boolean
    donghoid: number
    maHD: string
    mamdsD_2: string
    diachi: string
    mdsd: string
    tenDuong: string
    tenKhoiPhuongQuan: string
    ngayDangKyGhi: number
    choPhepDangKyNgayGhi: boolean
    sttu: number
};
