class ViewLapDatMoi {
    phieuYeuCauID!: number;
    id!: string
    maddk!: string
    maddktong!: string
    makv!: string
    tenkh!: string
    diachild!: string
    sonha!: string
    madpld!: string
    makhoi!: string
    maphuong!: string
    dienthoai!: string
    maquan!: string
    mamdsd!: string
    ngaydk!: Date
    ngayhks!: Date
    ngaydt!: Date
    ttdk!: string
    ttpl!: string
    tttk!: string
    ttct!: string
    ttxndt!: string
    tthd!: string
    ttxvt!: string
    ttdktc!: string
    tttc!: string
    ttkt!: string
    ttqt!: string
    loaidk!: string
    mst!: string
    sdInfo_INHOADON!: Boolean
    tenkH_INHOADON!: string
    diachI_INHOADON!: string
    didong!: string
    cmnd!: string
    noicapcmnd!: string
    ngaycapcmnd!: Date
    soho!: number
    kC_C3_2_DN!: number
    kC_DH_DN!: number
    idkh!: string
    chiphI_KH!: Boolean
    ngayTC!: Date
    cmndNgayCap!: Date
    cmndNoiCap!: string
    giaySuDungDat!: string
    hoKhauThuongTru!: string
    hinhThucLapDat!: string
    maKhachHangDauNoiLai!: string
    nhuCauSuDungNuoc!: string
    qsddaT_DiaChiLoDat!: string
    qsddaT_HoTen!: string
    qsddaT_LoaiGiayChungNhan!: string
    qsddaT_NgayCap!: Date
    qsddaT_NoiDungKhac!: string
    qsddaT_SoGiayChungNhan!: string
    thoiGianKhachHangCanLapMoi!: Date
    hoanThanhThongTinDaiDienKyHopDong!: Boolean
    hoanThanhMucDichSuDungNuoc!: Boolean
    hoanThanhNhuCauSuDungNuoc!: Boolean
    hoanThanhQuyenSuDungDat!: Boolean
    hoanThanhThongTinDiaChiLapDat!: Boolean
    hoanThanhViTriCapNguon!: Boolean
    isck!: Boolean
    ishaigia!: Boolean
    istl!: Boolean
    kophimt!: Boolean
    kophitn!: Boolean
    m3CQ!: number
    m3KD!: number
    m3SH!: number
    m3SX!: number
    nhothu!: Boolean
    sonk!: number
    tlck!: number
    tlcq!: number
    tlkd!: number
    tlsh!: number
    tlsx!: number
    hoanThanhDuToanBocVatTu!: Boolean
    acc!: number
    hokhaU_MADPLD!: string
    hokhaU_MAKHOI!: string
    hokhaU_SONHA!: string
    hoanThanhLichSuSuDungNuoc!: Boolean
    nguoN_ChuSoHuu!: string
    nguoN_KICHTHUOC!: number
    pointLat!: number
    pointLon!: number
    mucDichSuDungNuoc!: string
    hoanThanhDuToanBocVatTuCongTy!: Boolean
    hoanThanhDuToanBocVatTuKhachHang!: Boolean
    daohT_TrachNhiemKH!: Boolean
    daohT_QuyCach!: string
    daohT_KhoiLuong!: string
    daohT_ThoiGian!: Date
    thoiGianTo2NhanTin!: Date
    hoanThanhDuToanDaoHoanTra!: Boolean
    tongtieN_KH!: number
    tongtieN_CT!: number
    tongtieN_CTY_KH!: number
    tongtieN_VT_KH!: number
    tongtieN_DH_KH!: number
    nv_khaosat_hoten!: string
    nv_khaosat_manv!: string
    tongTienKHDC!: number
    tongTienCTDC!: number
    tongTienDC!: number
    tongTienVatTuKHDC!: number
    tongTienDaoKHDC!: number;

    qsddaT_KHONGDUDIEUKIEN!: Boolean
    qsddaT_LYDOKHONGDU!: string
    nhucaU_KHONGDUDIEUKIEN!: Boolean
    nhucaU_LYDOKHONGDU!: string
    nguoN_KHONGDUDIEUKIEN!: Boolean
    nguoN_LYDOKHONGDU!: string
    choNhuCauSuDung!: Boolean
    choTimMaKhachHang!: Boolean
    choKhachHangNopTien!: Boolean

    isHuy!: Boolean
    thoiGianHuy!: Date
    lyDoHuy!: string

    tongtieN_KHACHHANG!: number
}

export default ViewLapDatMoi;
