class ViewCaiTaoDongHo {
    id!: string
    maddk!: string
    makv!: string
    manh!: string
    tenkh!: string
    diachild!: string
    sonha!: string
    madpld!: string
    makhoi!: string
    maphuong!: string
    dienthoai!: string
    didong!: string
    maquan!: string
    ngaydk!: Date
    ngayhks!: Date
    ngaydt!: Date
    ttdk!: string
    ttpl!: string
    tttk!: string
    ttct!: string
    ttxndt!: string
    tthd!: string
    ttxvt!: string
    ttdktc!: string
    tttc!: string
    ttkt!: string
    ttqt!: string
    loaidk!: string
    pointLat!: number
    pointLon!: number
    hoanThanhDuToanBocVatTuCongTy!: boolean
    hoanThanhDuToanBocVatTuKhachHang!: boolean
    hoanThanhDuToanDaoHoanTra!: boolean
    daohT_TrachNhiemKH!: boolean
    daohT_QuyCach!: string
    daohT_KhoiLuong!: string
    daohT_ThoiGian!: Date
    isHuy!: boolean
    lyDoHuy!: string
    thoiGianHuy!: Date
    maPhieuHoanUng!: number
    tthu!: string
    maDuToan!: string
    idkh!: string
    phieuYeuCauID!: number
    nv_khaosat_manv!: string
    nv_khaosat_hoten!: string

    tongtieN_KH!: number
    tongtieN_CT!: number
    tongtieN_CTY_KH!: number
    tongtieN_VT_KH!: number
    tongtieN_DH_KH!: number
    tongtieN_KHACHHANG!: number
    dhT_KH!: number
    dhT_KH_TL!: number
    dhT_TT_KH!: number
    dhT_BS_KH!: number
    dhT_CTY!: number
    hienTrangDongHo!: string
    thoiGianDuKienThayThe!: Date

    khoiLuongThoaThuanVoiKhachHang!: number;
    chiSoKyThuTienGanNhat!: number
    chiSoDongHoNhapKho!: number
    chiSoMatDongHo!: number
    khoiLuongGoiY!: number
}

export default ViewCaiTaoDongHo;
